use crate::engine::abilities::Abilities;
use crate::engine::items::Items;
use crate::pokemon::PokemonName;
use crate::state::PokemonType;

pub struct MegaEvolveData {
    pub id: PokemonName,
    pub types: (PokemonType, PokemonType),
    pub ability: Abilities,
    pub base_stats: (i16, i16, i16, i16, i16, i16),
}

impl PokemonName {
    /*
    Base Stats are only required to re-calculate stats when a pokemon changes forme
    so not every pokemon will be here
    */
    pub fn base_stats(&self) -> (i16, i16, i16, i16, i16, i16) {
        match self {
            PokemonName::MINIOR => (60, 100, 60, 100, 60, 120),
            PokemonName::MINIORMETEOR => (60, 60, 100, 60, 100, 60),
            PokemonName::WISHIWASHI => (45, 20, 20, 25, 25, 40),
            PokemonName::WISHIWASHISCHOOL => (45, 140, 130, 140, 135, 30),
            PokemonName::PALAFIN => (100, 70, 72, 53, 62, 100),
            PokemonName::PALAFINHERO => (100, 160, 97, 106, 87, 100),
            PokemonName::EISCUE => (75, 80, 110, 65, 90, 50),
            PokemonName::EISCUENOICE => (75, 80, 70, 65, 50, 130),

            // megas
            PokemonName::VENUSAURMEGA => (80, 100, 123, 122, 120, 80),
            PokemonName::CHARIZARDMEGAX => (78, 130, 111, 130, 85, 100),
            PokemonName::CHARIZARDMEGAY => (78, 104, 78, 159, 115, 100),
            PokemonName::BLASTOISEMEGA => (79, 103, 120, 135, 115, 78),
            PokemonName::BEEDRILLMEGA => (65, 150, 40, 15, 80, 145),
            PokemonName::PIDGEOTMEGA => (83, 80, 80, 135, 80, 121),
            PokemonName::ALAKAZAMMEGA => (55, 50, 65, 175, 105, 150),
            PokemonName::SLOWBROMEGA => (95, 75, 180, 130, 80, 30),
            PokemonName::GENGARMEGA => (60, 65, 80, 170, 95, 130),
            PokemonName::KANGASKHANMEGA => (105, 125, 100, 60, 100, 100),
            PokemonName::PINSIRMEGA => (65, 155, 120, 65, 90, 105),
            PokemonName::GYARADOSMEGA => (95, 155, 109, 70, 130, 81),
            PokemonName::AERODACTYLMEGA => (80, 135, 85, 70, 95, 150),
            PokemonName::MEWTWOMEGAX => (106, 190, 100, 154, 100, 130),
            PokemonName::MEWTWOMEGAY => (106, 150, 70, 194, 120, 140),
            PokemonName::AMPHAROSMEGA => (90, 95, 105, 165, 110, 45),
            PokemonName::STEELIXMEGA => (75, 125, 230, 55, 95, 30),
            PokemonName::SCIZORMEGA => (70, 150, 140, 65, 100, 75),
            PokemonName::HERACROSSMEGA => (80, 185, 115, 40, 105, 75),
            PokemonName::HOUNDOOMMEGA => (75, 90, 90, 140, 90, 115),
            PokemonName::TYRANITARMEGA => (100, 164, 150, 95, 120, 71),
            PokemonName::SCEPTILEMEGA => (70, 110, 75, 145, 85, 145),
            PokemonName::BLAZIKENMEGA => (80, 160, 80, 130, 80, 100),
            PokemonName::SWAMPERTMEGA => (100, 150, 110, 95, 110, 70),
            PokemonName::GARDEVOIRMEGA => (68, 85, 65, 165, 135, 100),
            PokemonName::SABLEYEMEGA => (50, 85, 125, 85, 115, 20),
            PokemonName::MAWILEMEGA => (50, 105, 125, 55, 95, 50),
            PokemonName::AGGRONMEGA => (70, 140, 230, 60, 80, 50),
            PokemonName::MEDICHAMMEGA => (60, 100, 85, 80, 85, 100),
            PokemonName::MANECTRICMEGA => (70, 75, 80, 135, 80, 135),
            PokemonName::SHARPEDOMEGA => (70, 140, 70, 110, 65, 105),
            PokemonName::CAMERUPTMEGA => (70, 120, 100, 145, 105, 20),
            PokemonName::ALTARIAMEGA => (75, 110, 110, 110, 105, 80),
            PokemonName::BANETTEMEGA => (64, 165, 75, 93, 83, 75),
            PokemonName::ABSOLMEGA => (65, 150, 60, 115, 60, 115),
            PokemonName::GLALIEMEGA => (80, 120, 80, 120, 80, 100),
            PokemonName::SALAMENCEMEGA => (95, 145, 130, 120, 90, 120),
            PokemonName::METAGROSSMEGA => (80, 145, 150, 105, 110, 110),
            PokemonName::LATIASMEGA => (80, 100, 120, 140, 150, 110),
            PokemonName::LATIOSMEGA => (80, 130, 100, 160, 120, 110),
            PokemonName::RAYQUAZAMEGA => (105, 180, 100, 180, 100, 115),
            PokemonName::LOPUNNYMEGA => (65, 136, 94, 54, 96, 135),
            PokemonName::GARCHOMPMEGA => (108, 170, 115, 120, 95, 92),
            PokemonName::LUCARIOMEGA => (70, 145, 88, 140, 70, 112),
            PokemonName::ABOMASNOWMEGA => (90, 132, 105, 132, 105, 30),
            PokemonName::GALLADEMEGA => (68, 165, 95, 65, 115, 110),
            PokemonName::AUDINOMEGA => (103, 60, 126, 80, 126, 50),
            PokemonName::DIANCIEMEGA => (50, 160, 110, 160, 110, 110),
            _ => panic!("Base stats not implemented for {}", self),
        }
    }

    pub fn mega_evolve_target(&self, item: Items) -> Option<MegaEvolveData> {
        match (self, item) {
            (PokemonName::VENUSAUR, Items::VENUSAURITE) => Some(MegaEvolveData {
                id: PokemonName::VENUSAURMEGA,
                types: (PokemonType::GRASS, PokemonType::POISON),
                ability: Abilities::THICKFAT,
                base_stats: (80, 100, 123, 122, 120, 80),
            }),
            (PokemonName::CHARIZARD, Items::CHARIZARDITEX) => Some(MegaEvolveData {
                id: PokemonName::CHARIZARDMEGAX,
                types: (PokemonType::FIRE, PokemonType::DRAGON),
                ability: Abilities::TOUGHCLAWS,
                base_stats: (78, 130, 111, 130, 85, 100),
            }),
            (PokemonName::CHARIZARD, Items::CHARIZARDITEY) => Some(MegaEvolveData {
                id: PokemonName::CHARIZARDMEGAY,
                types: (PokemonType::FIRE, PokemonType::FLYING),
                ability: Abilities::DROUGHT,
                base_stats: (78, 104, 78, 159, 115, 100),
            }),
            (PokemonName::BLASTOISE, Items::BLASTOISINITE) => Some(MegaEvolveData {
                id: PokemonName::BLASTOISEMEGA,
                types: (PokemonType::WATER, PokemonType::TYPELESS),
                ability: Abilities::MEGALAUNCHER,
                base_stats: (79, 103, 120, 135, 115, 78),
            }),
            (PokemonName::BEEDRILL, Items::BEEDRILLITE) => Some(MegaEvolveData {
                id: PokemonName::BEEDRILLMEGA,
                types: (PokemonType::BUG, PokemonType::POISON),
                ability: Abilities::ADAPTABILITY,
                base_stats: (65, 150, 40, 15, 80, 145),
            }),
            (PokemonName::PIDGEOT, Items::PIDGEOTITE) => Some(MegaEvolveData {
                id: PokemonName::PIDGEOTMEGA,
                types: (PokemonType::NORMAL, PokemonType::FLYING),
                ability: Abilities::NOGUARD,
                base_stats: (83, 80, 80, 135, 80, 121),
            }),
            (PokemonName::ALAKAZAM, Items::ALAKAZITE) => Some(MegaEvolveData {
                id: PokemonName::ALAKAZAMMEGA,
                types: (PokemonType::PSYCHIC, PokemonType::TYPELESS),
                ability: Abilities::TRACE,
                base_stats: (55, 50, 65, 175, 105, 150),
            }),
            (PokemonName::SLOWBRO, Items::SLOWBRONITE) => Some(MegaEvolveData {
                id: PokemonName::SLOWBROMEGA,
                types: (PokemonType::WATER, PokemonType::PSYCHIC),
                ability: Abilities::SHELLARMOR,
                base_stats: (95, 75, 180, 130, 80, 30),
            }),
            (PokemonName::GENGAR, Items::GENGARITE) => Some(MegaEvolveData {
                id: PokemonName::GENGARMEGA,
                types: (PokemonType::GHOST, PokemonType::POISON),
                ability: Abilities::SHADOWTAG,
                base_stats: (60, 65, 80, 170, 95, 130),
            }),
            (PokemonName::KANGASKHAN, Items::KANGASKHANITE) => Some(MegaEvolveData {
                id: PokemonName::KANGASKHANMEGA,
                types: (PokemonType::NORMAL, PokemonType::TYPELESS),
                ability: Abilities::PARENTALBOND,
                base_stats: (105, 125, 100, 60, 100, 100),
            }),
            (PokemonName::PINSIR, Items::PINSIRITE) => Some(MegaEvolveData {
                id: PokemonName::PINSIRMEGA,
                types: (PokemonType::BUG, PokemonType::FLYING),
                ability: Abilities::AERILATE,
                base_stats: (65, 155, 120, 65, 90, 105),
            }),
            (PokemonName::GYARADOS, Items::GYARADOSITE) => Some(MegaEvolveData {
                id: PokemonName::GYARADOSMEGA,
                types: (PokemonType::WATER, PokemonType::DARK),
                ability: Abilities::MOLDBREAKER,
                base_stats: (95, 155, 109, 70, 130, 81),
            }),
            (PokemonName::AERODACTYL, Items::AERODACTYLITE) => Some(MegaEvolveData {
                id: PokemonName::AERODACTYLMEGA,
                types: (PokemonType::ROCK, PokemonType::FLYING),
                ability: Abilities::TOUGHCLAWS,
                base_stats: (80, 135, 85, 70, 95, 150),
            }),
            (PokemonName::MEWTWO, Items::MEWTWONITEX) => Some(MegaEvolveData {
                id: PokemonName::MEWTWOMEGAX,
                types: (PokemonType::PSYCHIC, PokemonType::FIGHTING),
                ability: Abilities::STEADFAST,
                base_stats: (106, 190, 100, 154, 100, 130),
            }),
            (PokemonName::MEWTWO, Items::MEWTWONITEY) => Some(MegaEvolveData {
                id: PokemonName::MEWTWOMEGAY,
                types: (PokemonType::PSYCHIC, PokemonType::TYPELESS),
                ability: Abilities::INSOMNIA,
                base_stats: (106, 150, 70, 194, 120, 140),
            }),
            (PokemonName::AMPHAROS, Items::AMPHAROSITE) => Some(MegaEvolveData {
                id: PokemonName::AMPHAROSMEGA,
                types: (PokemonType::ELECTRIC, PokemonType::DRAGON),
                ability: Abilities::MOLDBREAKER,
                base_stats: (90, 95, 105, 165, 110, 45),
            }),
            (PokemonName::STEELIX, Items::STEELIXITE) => Some(MegaEvolveData {
                id: PokemonName::STEELIXMEGA,
                types: (PokemonType::STEEL, PokemonType::GROUND),
                ability: Abilities::SANDFORCE,
                base_stats: (75, 125, 230, 55, 95, 30),
            }),
            (PokemonName::SCIZOR, Items::SCIZORITE) => Some(MegaEvolveData {
                id: PokemonName::SCIZORMEGA,
                types: (PokemonType::BUG, PokemonType::STEEL),
                ability: Abilities::TECHNICIAN,
                base_stats: (70, 150, 140, 65, 100, 75),
            }),
            (PokemonName::HERACROSS, Items::HERACRONITE) => Some(MegaEvolveData {
                id: PokemonName::HERACROSSMEGA,
                types: (PokemonType::BUG, PokemonType::FIGHTING),
                ability: Abilities::SKILLLINK,
                base_stats: (80, 185, 115, 40, 105, 75),
            }),
            (PokemonName::HOUNDOOM, Items::HOUNDOOMINITE) => Some(MegaEvolveData {
                id: PokemonName::HOUNDOOMMEGA,
                types: (PokemonType::DARK, PokemonType::FIRE),
                ability: Abilities::SOLARPOWER,
                base_stats: (75, 90, 90, 140, 90, 115),
            }),
            (PokemonName::TYRANITAR, Items::TYRANITARITE) => Some(MegaEvolveData {
                id: PokemonName::TYRANITARMEGA,
                types: (PokemonType::ROCK, PokemonType::DARK),
                ability: Abilities::SANDSTREAM,
                base_stats: (100, 164, 150, 95, 120, 71),
            }),
            (PokemonName::SCEPTILE, Items::SCEPTILITE) => Some(MegaEvolveData {
                id: PokemonName::SCEPTILEMEGA,
                types: (PokemonType::GRASS, PokemonType::DRAGON),
                ability: Abilities::LIGHTNINGROD,
                base_stats: (70, 110, 75, 145, 85, 145),
            }),
            (PokemonName::BLAZIKEN, Items::BLAZIKENITE) => Some(MegaEvolveData {
                id: PokemonName::BLAZIKENMEGA,
                types: (PokemonType::FIRE, PokemonType::FIGHTING),
                ability: Abilities::SPEEDBOOST,
                base_stats: (80, 160, 80, 130, 80, 100),
            }),
            (PokemonName::SWAMPERT, Items::SWAMPERTITE) => Some(MegaEvolveData {
                id: PokemonName::SWAMPERTMEGA,
                types: (PokemonType::WATER, PokemonType::GROUND),
                ability: Abilities::SWIFTSWIM,
                base_stats: (100, 150, 110, 95, 110, 70),
            }),
            (PokemonName::GARDEVOIR, Items::GARDEVOIRITE) => Some(MegaEvolveData {
                id: PokemonName::GARDEVOIRMEGA,
                types: (PokemonType::PSYCHIC, PokemonType::FAIRY),
                ability: Abilities::PIXILATE,
                base_stats: (68, 85, 65, 165, 135, 100),
            }),
            (PokemonName::SABLEYE, Items::SABLENITE) => Some(MegaEvolveData {
                id: PokemonName::SABLEYEMEGA,
                types: (PokemonType::DARK, PokemonType::GHOST),
                ability: Abilities::MAGICBOUNCE,
                base_stats: (50, 85, 125, 85, 115, 20),
            }),
            (PokemonName::MAWILE, Items::MAWILITE) => Some(MegaEvolveData {
                id: PokemonName::MAWILEMEGA,
                types: (PokemonType::STEEL, PokemonType::FAIRY),
                ability: Abilities::HUGEPOWER,
                base_stats: (50, 105, 125, 55, 95, 50),
            }),
            (PokemonName::AGGRON, Items::AGGRONITE) => Some(MegaEvolveData {
                id: PokemonName::AGGRONMEGA,
                types: (PokemonType::STEEL, PokemonType::TYPELESS),
                ability: Abilities::FILTER,
                base_stats: (70, 140, 230, 60, 80, 50),
            }),
            (PokemonName::MEDICHAM, Items::MEDICHAMITE) => Some(MegaEvolveData {
                id: PokemonName::MEDICHAMMEGA,
                types: (PokemonType::FIGHTING, PokemonType::PSYCHIC),
                ability: Abilities::PUREPOWER,
                base_stats: (60, 100, 85, 80, 85, 100),
            }),
            (PokemonName::MANECTRIC, Items::MANECTITE) => Some(MegaEvolveData {
                id: PokemonName::MANECTRICMEGA,
                types: (PokemonType::ELECTRIC, PokemonType::TYPELESS),
                ability: Abilities::INTIMIDATE,
                base_stats: (70, 75, 80, 135, 80, 135),
            }),
            (PokemonName::SHARPEDO, Items::SHARPEDONITE) => Some(MegaEvolveData {
                id: PokemonName::SHARPEDOMEGA,
                types: (PokemonType::WATER, PokemonType::DARK),
                ability: Abilities::STRONGJAW,
                base_stats: (70, 140, 70, 110, 65, 105),
            }),
            (PokemonName::CAMERUPT, Items::CAMERUPTITE) => Some(MegaEvolveData {
                id: PokemonName::CAMERUPTMEGA,
                types: (PokemonType::FIRE, PokemonType::GROUND),
                ability: Abilities::SHEERFORCE,
                base_stats: (70, 120, 100, 145, 105, 20),
            }),
            (PokemonName::ALTARIA, Items::ALTARIANITE) => Some(MegaEvolveData {
                id: PokemonName::ALTARIAMEGA,
                types: (PokemonType::DRAGON, PokemonType::FAIRY),
                ability: Abilities::PIXILATE,
                base_stats: (75, 110, 110, 110, 105, 80),
            }),
            (PokemonName::BANETTE, Items::BANETTITE) => Some(MegaEvolveData {
                id: PokemonName::BANETTEMEGA,
                types: (PokemonType::GHOST, PokemonType::TYPELESS),
                ability: Abilities::PRANKSTER,
                base_stats: (64, 165, 75, 93, 83, 75),
            }),
            (PokemonName::ABSOL, Items::ABSOLITE) => Some(MegaEvolveData {
                id: PokemonName::ABSOLMEGA,
                types: (PokemonType::DARK, PokemonType::TYPELESS),
                ability: Abilities::MAGICBOUNCE,
                base_stats: (65, 150, 60, 115, 60, 115),
            }),
            (PokemonName::GLALIE, Items::GLALITITE) => Some(MegaEvolveData {
                id: PokemonName::GLALIEMEGA,
                types: (PokemonType::ICE, PokemonType::TYPELESS),
                ability: Abilities::REFRIGERATE,
                base_stats: (80, 120, 80, 120, 80, 100),
            }),
            (PokemonName::SALAMENCE, Items::SALAMENCITE) => Some(MegaEvolveData {
                id: PokemonName::SALAMENCEMEGA,
                types: (PokemonType::DRAGON, PokemonType::FLYING),
                ability: Abilities::AERILATE,
                base_stats: (95, 145, 130, 120, 90, 120),
            }),
            (PokemonName::METAGROSS, Items::METAGROSSITE) => Some(MegaEvolveData {
                id: PokemonName::METAGROSSMEGA,
                types: (PokemonType::STEEL, PokemonType::PSYCHIC),
                ability: Abilities::TOUGHCLAWS,
                base_stats: (80, 145, 150, 105, 110, 110),
            }),
            (PokemonName::LATIAS, Items::LATIASITE) => Some(MegaEvolveData {
                id: PokemonName::LATIASMEGA,
                types: (PokemonType::DRAGON, PokemonType::PSYCHIC),
                ability: Abilities::LEVITATE,
                base_stats: (80, 100, 120, 140, 150, 110),
            }),
            (PokemonName::LATIOS, Items::LATIOSITE) => Some(MegaEvolveData {
                id: PokemonName::LATIOSMEGA,
                types: (PokemonType::DRAGON, PokemonType::PSYCHIC),
                ability: Abilities::LEVITATE,
                base_stats: (80, 130, 100, 160, 120, 110),
            }),
            (PokemonName::LOPUNNY, Items::LOPUNNITE) => Some(MegaEvolveData {
                id: PokemonName::LOPUNNYMEGA,
                types: (PokemonType::NORMAL, PokemonType::FIGHTING),
                ability: Abilities::SCRAPPY,
                base_stats: (65, 136, 94, 54, 96, 135),
            }),
            (PokemonName::GARCHOMP, Items::GARCHOMPITE) => Some(MegaEvolveData {
                id: PokemonName::GARCHOMPMEGA,
                types: (PokemonType::DRAGON, PokemonType::GROUND),
                ability: Abilities::SANDFORCE,
                base_stats: (108, 170, 115, 120, 95, 92),
            }),
            (PokemonName::LUCARIO, Items::LUCARIONITE) => Some(MegaEvolveData {
                id: PokemonName::LUCARIOMEGA,
                types: (PokemonType::FIGHTING, PokemonType::STEEL),
                ability: Abilities::ADAPTABILITY,
                base_stats: (70, 145, 88, 140, 70, 112),
            }),
            (PokemonName::ABOMASNOW, Items::ABOMASITE) => Some(MegaEvolveData {
                id: PokemonName::ABOMASNOWMEGA,
                types: (PokemonType::GRASS, PokemonType::ICE),
                ability: Abilities::SNOWWARNING,
                base_stats: (90, 132, 105, 132, 105, 30),
            }),
            (PokemonName::GALLADE, Items::GALLADITE) => Some(MegaEvolveData {
                id: PokemonName::GALLADEMEGA,
                types: (PokemonType::PSYCHIC, PokemonType::FIGHTING),
                ability: Abilities::INNERFOCUS,
                base_stats: (68, 165, 95, 65, 115, 110),
            }),
            (PokemonName::AUDINO, Items::AUDINITE) => Some(MegaEvolveData {
                id: PokemonName::AUDINOMEGA,
                types: (PokemonType::NORMAL, PokemonType::FAIRY),
                ability: Abilities::HEALER,
                base_stats: (103, 60, 126, 80, 126, 50),
            }),
            (PokemonName::DIANCIE, Items::DIANCITE) => Some(MegaEvolveData {
                id: PokemonName::DIANCIEMEGA,
                types: (PokemonType::ROCK, PokemonType::FAIRY),
                ability: Abilities::MAGICBOUNCE,
                base_stats: (50, 160, 110, 160, 110, 110),
            }),
            _ => None,
        }
    }
}
